server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanjuthomas/config-store
          search-paths:
            - jobs-service
            - news-service
            - profile-service
            - attorney-service
          default-label: develop